version: '3.4'

services:

    frontend:
      image: rogerspizza:latest
      environment: 
       - ProductEndpoint=http://backend:8080
      ports:
        - "32000:8080"
      depends_on: 
        - backend
    backend:
      image: rogerspizza:latest
      ports:
        - "32001:8080"
